### ISSUE TITLE
Reference formatting is off in some RFCs

### ISSUE THREAD

**Issue by larseggert** [martinthomson/rfc-txt-html#13]
See https://datatracker.ietf.org/doc/html/rfc8719#name-informative-references
<img width="711" alt="Screenshot 2023-08-09 at 20 26 23" src="https://github.com/martinthomson/rfc-txt-html/assets/200328/0cb7c6b4-62b9-4eb3-8cd0-9a370a9858ac">
vs. the text version
<img width="585" alt="Screenshot 2023-08-09 at 20 26 41" src="https://github.com/martinthomson/rfc-txt-html/assets/200328/d3646b46-261e-4e32-8df0-2e5f9a5ac8c5">

**Comment by martinthomson** [comment]
Interesting.  

The line wrapping for [CONT_DIST] is one thing.  I don't know how to do that with CSS.  It's worth looking into though, because it's probably neater that way.

The line wrapping ahead of the long URLs is another.  For [CONT-DIST] that is probably just luck, but the choice of URL placement for [IETFMEET] is a curious choice.  I don't know how to do that either, but I'm not sure that it is worthwhile attempting it.  (As you already know, line wrapping behaviour in browsers is not very consistent, so this would be a real challenge.)

**Comment by larseggert** [comment]
I'm fine with wontfix, just wanted to flag it.

**Comment by martinthomson** [comment]
<details>
<summary>I worked something out with flexbox haxx</summary>

```html
<div class="x">............</div>
<div class="f">
  <div class="l">1234567890</div>
  <div class="r">
    Enim quidem amet sunt nam iste rerum dicta aut. Sit est est qui dolore.
    Nulla iste officiis totam dolor. Expedita esse quia quasi tempora eum
    quisquam dolorem. Nihil praesentium repellat nihil ad ut ab nemo. Cum vel
    est hic et.
  </div>
  <div class="s"></div>
  <div class="l">123</div>
  <div class="r">
    Enim quidem amet sunt nam iste rerum dicta aut. Sit est est qui dolore.
    Nulla iste officiis totam dolor. Expedita esse quia quasi tempora eum
    quisquam dolorem. Nihil praesentium repellat nihil ad ut ab nemo. Cum vel
    est hic et.
  </div>
  <div class="s"></div>
  <div class="l">12345</div>
  <div class="r">
    Enim quidem amet sunt nam iste rerum dicta aut. Sit est est qui dolore.
    Nulla iste officiis totam dolor. Expedita esse quia quasi tempora eum
    quisquam dolorem. Nihil praesentium repellat nihil ad ut ab nemo. Cum vel
    est hic et.
  </div>
</div>
<div class="x">............</div>
<div class="f">
  <div class="l">123</div>
  <div class="r">
    Enim quidem amet sunt nam iste rerum dicta aut. Sit est est qui dolore.
    Nulla iste officiis totam dolor. Expedita esse quia quasi tempora eum
    quisquam dolorem. Nihil praesentium repellat nihil ad ut ab nemo. Cum vel
    est hic et.
  </div>
  <div class="s"></div>
  <div class="l">123456789</div>
  <div class="r">
    Enim quidem amet sunt nam iste rerum dicta aut. Sit est est qui dolore.
    Nulla iste officiis totam dolor. Expedita esse quia quasi tempora eum
    quisquam dolorem. Nihil praesentium repellat nihil ad ut ab nemo. Cum vel
    est hic et.
  </div>
  <div class="s"></div>
  <div class="l">12345</div>
  <div class="r">
    Enim quidem amet sunt nam iste rerum dicta aut. Sit est est qui dolore.
    Nulla iste officiis totam dolor. Expedita esse quia quasi tempora eum
    quisquam dolorem. Nihil praesentium repellat nihil ad ut ab nemo. Cum vel
    est hic et.
  </div>
</div>
<div class="x">............</div>

```

```css
:root {
  font-family: monospace;
}
.x {
  width: 72ch;
  color: #eee;
  background-color: #bbb;
}
.l {
  background: rgb(255, 0, 0, 0.1);
}
.r {
  background: rgb(0, 0, 255, 0.1);
}
.f {
  display: flex;
  flex-flow: row wrap;
  width: 64ch;
  padding-left: 8ch;
}
.f .l {
  flex: 0 0 max-content;
  min-width: 8ch;
  margin-left: -8ch;
}
.f .r {
  flex: 0 0 63ch;
  padding-left: 1ch;
  clear: right;
}
.f .s {
  flex: 0 0 72ch;
  height: 0;
}

```

</details>

It depends on the `<dd class="break">` that is added by xml2rfc, which I don't like, but it seems to do the job pretty well.
