### ISSUE TITLE
Split it up?

### ISSUE THREAD

**Issue by larseggert** [martinthomson/rfc-txt-html#3]
It would be neat if you split this up into the part I need for https://github.com/ietf-tools/datatracker/blob/17fc283944a0e01667012c11b2ef1d57de973b80/ietf/static/css/document_html_txt.scss and into a second file with whatever `xml2rfc` needs. Easier to keep in sync.

**Comment by martinthomson** [comment]
I'm looking at that file and it seems like you have a need for the variables (in your `:root`) and the content of the `.rfchtml` block.

I can rearrange things a little so that it leans more heavily on the new classes that xml2rfc produces in HTML.  Rather than `body`, I can use `.xml2rfc` (if that is OK with you), so that I would have something like...

```css
.xml2rfc {
  --line: 1.2em;
  --block: 0 0 0 3ch;
  --paragraph: var(--line) 0 var(--line) 3ch;
  /* body rules that really belong here */
}
```

Is it important that you use the `rfchtml` class over the `xml2rfc` one?

The other `body` rules can probably just go entirely.  Those are - I believe - defaults anyway.

I don't know how to deal with your other modifications though.  You are using mixins for setting margins.  I don't think that I'm ready to jump to requiring a preprocessor, but I might just expand those uses of `margin` that seem to have affected WeasyPrint.

All told, that would mean that you have a file that is usable as a drop-in and I don't have to split anything.  Would that work?
