### ISSUE TITLE
Avoid CSS grid

### ISSUE THREAD

**Issue by larseggert** [martinthomson/rfc-txt-html#4]
Is there a way to avoid using CSS grids? Weasyprint, which the datatracker uses to make PDFs, doesn't support that.

**Comment by martinthomson** [comment]
I am using `@supports(display: grid)` in the latest version.  Does WeasyPrint not support `@supports`?  The fallback doesn't look exactly the same, but it should still print something coherent.

I know that this is not ideal, but I wasn't able to get the presentation right without it.  Remember the problem where the authors block spilled down over the title when there were too many authors?

**Comment by larseggert** [comment]
I don't think `@supports` is supported: https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#css

**Comment by martinthomson** [comment]
Yuck.  This is really needed to do any sort of switch-hitting when features aren't supported.  [All the browsers](https://caniuse.com/css-featurequeries) do fine with this, and have done for ages.

**Comment by larseggert** [comment]
I'm trying to work around it by using `@media print` instead of checking for grid support.

**Comment by larseggert** [comment]
But with little success. This is what I have now:
``` css
/* #identifiers styling for when grid layout is supported, or not */
@media screen {
/* @supports(display: grid) { */
  #identifiers {
    display: grid;
    grid-template-columns: 47ch 24ch;
    grid-auto-rows: auto;
    gap: 0 1ch;
  }
  #identifiers dd {
    grid-column: 1;
  }
  #identifiers dd.authors {
    grid-area: 1 / 2 / 100 / 3;
    width: 24ch;
    text-align: right;
    display: block;
  }
}
@media print {
/* @supports not (display: grid) { */
  /* is this being used? */
  * { color: red !important; }
  #identifiers dd.authors {
    padding-left: 8ch;
    width: 64ch;
  }
  #identifiers dd.authors::before {
    content: "Authors:";
    margin: 0 0 0 -8ch;
  }
  #identifiers dd.authors .author {
    display: inline-block;
    margin: 0 2ch 0 1ch;
  }
  #identifiers dd.authors .author:last-of-type {
    margin-right: 0;
  }
}
```
It's all red, so the `print` styles are used, but the layout is still broken:
<img width="806" alt="Screenshot 2022-12-15 at 12 27 50" src="https://user-images.githubusercontent.com/200328/207836777-a7e54009-ff07-4b3f-b2be-f23fd55a8a75.png">
